dev:
  server:
    port: ":8082"
  kafka:
    servers: "localhost:9092"
    consumers:
    - consumerGroup: "sample-consumer"
      concurrency: 10
      cron: "*/2 * * * *"
      durationMinute: 1
      maxRetry: 3
      topics:
        - "sample-topic"
      exceptionTopic:
        topic: "sample-exception-topic"
        concurrency: 1