dev:
  server:
    port: ":8082"
  kafka:
    servers: "localhost:29092"
    consumer:
      consumerGroup: "sample-consumer"
      concurrency: 10
      topics:
        - "sample-topic"
      exceptionTopic:
        topic: "sample-exception-topic"
        maxRetry: 3
        cron: "*/2 * * * *"
        durationMinute: 1
        concurrency: 1