kafka:
  brokers:
    - "127.0.0.1:9092"
  consumer:
    groupId: "sample-consumer-2"
    topic: "exception-2"
    deadLetterTopic: ""
    minBytes: 10e3
    maxBytes: 10e6
    maxRetry: 3
    maxWait: 2s
    commitInterval: 1s
    heartbeatInterval: 3s
    sessionTimeout: 30s
    rebalanceTimeout: 30s
    startOffset: "earliest" #earliest or latest
    retentionTime: 24h
    concurrency: 1
    cron: "*/1 * * * *"
    duration: 20s
  producer:
    batchSize: 100
    batchTimeout: 500us